AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Kondate Planner - Bedrock Agent for Meal Planning via Slack

Globals:
  Function:
    Runtime: python3.12
    Timeout: 30
    MemorySize: 256
    Architectures:
      - arm64
    Layers:
      - !Ref CommonLayer
    Environment:
      Variables:
        RECIPES_TABLE: !Ref RecipesTable
        HISTORY_TABLE: !Ref MenuHistoryTable

Resources:
  # ==================== DynamoDB Tables ====================
  RecipesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: kondate-recipes
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: recipe_id
          AttributeType: S
      KeySchema:
        - AttributeName: recipe_id
          KeyType: HASH

  MenuHistoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: kondate-menu-history
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: date
          AttributeType: S
      KeySchema:
        - AttributeName: date
          KeyType: HASH

  # ==================== Lambda Layer ====================
  CommonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: kondate-common-layer
      ContentUri: src/layers/common/
      CompatibleRuntimes:
        - python3.12
      LicenseInfo: 'MIT'
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: python3.12

  # ==================== Bedrock Agent Action Functions ====================
  GetRecipesActionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/agent_actions/get_recipes/
      Handler: app.lambda_handler
      Description: Bedrock Agent action to retrieve recipes
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref RecipesTable

  GetHistoryActionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/agent_actions/get_history/
      Handler: app.lambda_handler
      Description: Bedrock Agent action to retrieve menu history
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref MenuHistoryTable

  SaveMenuActionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/agent_actions/save_menu/
      Handler: app.lambda_handler
      Description: Bedrock Agent action to save menu to history
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MenuHistoryTable

  # ==================== S3 Bucket for Agent Schemas ====================
  AgentSchemasBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'kondate-agent-schemas-${AWS::AccountId}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled

  # ==================== Amazon Q / Chatbot IAM Role ====================
  AmazonQChatbotRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: kondate-amazonq-chatbot-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: chatbot.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchLogsReadOnlyAccess
      Policies:
        - PolicyName: InvokeBedrockAgent
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - bedrock:InvokeAgent
                  - bedrock:GetAgent
                  - bedrock:ListAgents
                Resource:
                  - !Sub 'arn:aws:bedrock:${AWS::Region}:${AWS::AccountId}:agent/*'
                  - !Sub 'arn:aws:bedrock:${AWS::Region}:${AWS::AccountId}:agent-alias/*/*'

  # ==================== Bedrock Agent IAM Role ====================
  BedrockAgentRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: kondate-bedrock-agent-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: bedrock.amazonaws.com
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                aws:SourceAccount: !Ref AWS::AccountId
              ArnLike:
                aws:SourceArn: !Sub 'arn:aws:bedrock:${AWS::Region}:${AWS::AccountId}:agent/*'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
      Policies:
        - PolicyName: InvokeActionLambdas
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: lambda:InvokeFunction
                Resource:
                  - !GetAtt GetRecipesActionFunction.Arn
                  - !GetAtt GetHistoryActionFunction.Arn
                  - !GetAtt SaveMenuActionFunction.Arn
        - PolicyName: InvokeFoundationModel
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                  - bedrock:InvokeModelWithResponseStream
                  - bedrock:GetInferenceProfile
                  - bedrock:GetFoundationModel
                Resource:
                  # Inference Profile (cross-region)
                  - !Sub 'arn:aws:bedrock:${AWS::Region}:${AWS::AccountId}:inference-profile/jp.anthropic.claude-sonnet-4-5-20250929-v1:0'
                  # Foundation models in both regions
                  - 'arn:aws:bedrock:ap-northeast-1::foundation-model/anthropic.claude-sonnet-4-5-20250929-v1:0'
                  - 'arn:aws:bedrock:ap-northeast-3::foundation-model/anthropic.claude-sonnet-4-5-20250929-v1:0'
        - PolicyName: ReadAgentSchemas
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Sub '${AgentSchemasBucket.Arn}/*'
                  - !GetAtt AgentSchemasBucket.Arn

  # ==================== Lambda Resource-based Policies (Allow Bedrock to invoke) ====================
  GetRecipesActionInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref GetRecipesActionFunction
      Action: lambda:InvokeFunction
      Principal: bedrock.amazonaws.com
      SourceAccount: !Ref AWS::AccountId

  GetHistoryActionInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref GetHistoryActionFunction
      Action: lambda:InvokeFunction
      Principal: bedrock.amazonaws.com
      SourceAccount: !Ref AWS::AccountId

  SaveMenuActionInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref SaveMenuActionFunction
      Action: lambda:InvokeFunction
      Principal: bedrock.amazonaws.com
      SourceAccount: !Ref AWS::AccountId

  # ==================== Bedrock Agent ====================
  # NOTE: Bedrock Agent and AgentAlias must be created manually or via AWS CLI
  # because CloudFormation support is limited. Use the outputs below to configure.
  #
  # To create the agent manually:
  # 1. Upload schemas to S3 (see outputs below)
  # 2. Go to Bedrock console → Agents → Create agent
  # 3. Use the configuration values from the outputs
  # 4. Configure AWS Chatbot to use the agent

Outputs:
  # ==================== DynamoDB ====================
  RecipesTableName:
    Description: "DynamoDB Recipes table name"
    Value: !Ref RecipesTable

  MenuHistoryTableName:
    Description: "DynamoDB Menu History table name"
    Value: !Ref MenuHistoryTable

  # ==================== Lambda Functions ====================
  GetRecipesActionFunctionArn:
    Description: "ARN of GetRecipesAction Lambda"
    Value: !GetAtt GetRecipesActionFunction.Arn

  GetHistoryActionFunctionArn:
    Description: "ARN of GetHistoryAction Lambda"
    Value: !GetAtt GetHistoryActionFunction.Arn

  SaveMenuActionFunctionArn:
    Description: "ARN of SaveMenuAction Lambda"
    Value: !GetAtt SaveMenuActionFunction.Arn

  # ==================== S3 Bucket ====================
  AgentSchemasBucketName:
    Description: "S3 bucket for agent schemas"
    Value: !Ref AgentSchemasBucket

  # ==================== IAM Roles ====================
  AmazonQChatbotRoleArn:
    Description: "IAM Role ARN for Amazon Q / Chatbot"
    Value: !GetAtt AmazonQChatbotRole.Arn

  BedrockAgentRoleArn:
    Description: "IAM Role ARN for Bedrock Agent"
    Value: !GetAtt BedrockAgentRole.Arn

  AgentInstructions:
    Description: "Instructions to paste into Bedrock Agent configuration"
    Value: |
      You are a helpful meal planning assistant that helps users create balanced Japanese meal plans.

      AVAILABLE RECIPES AND HISTORY:
      - Call get_recipes() to see all available recipes. You can optionally filter by category.
      - Call get_history() to see recent menus (default 30 days). Use this to avoid repeating recipes.

      MEAL PLANNING RULES:
      When generating menu suggestions:
      1. Breakfast: 1-2 dishes (e.g., rice + miso soup, or toast + salad)
      2. Lunch: 1-3 dishes (balanced meal or bento-style)
      3. Dinner: 2-3 dishes (main + side + soup is common)
      4. Variety: Don't repeat the same main protein on consecutive days
      5. Balance: Include vegetables in every meal when possible
      6. Cooking time: Mix quick recipes (<30min) with more involved ones

      RESPONSE FORMAT (IMPORTANT - For Slack compatibility):
      - Keep responses concise and well-structured
      - Use this compact format for menu suggestions:
        **1日目 (Day 1):**
        - 朝食: レシピ名1, レシピ名2
        - 昼食: レシピ名1, レシピ名2
        - 夕食: レシピ名1, レシピ名2, レシピ名3
      - Avoid repeating detailed recipe information (ingredients, cooking time, etc.)
      - Focus on recipe names and categories only
      - Keep additional commentary brief

      WORKFLOW:
      1. When user asks for menu suggestions, fetch recipes and recent history
      2. Generate a menu plan for the requested number of days (typically 3 or 7)
      3. Present the menu clearly with recipe names in compact format
      4. Ask: "この献立で保存しますか？ (Would you like me to save this menu?)"
      5. ONLY call save_menu() if user explicitly confirms (yes/はい/保存して/looks good/etc.)
      6. If user says no or requests changes, regenerate based on their feedback

      TONE:
      - Be friendly and conversational
      - Respond in Japanese or English based on user's language
      - Provide brief cooking tips or nutritional insights when relevant

  SchemaUploadCommands:
    Description: "Commands to upload schemas to S3"
    Value: !Sub |
      aws s3 cp src/schemas/get-recipes.yaml s3://${AgentSchemasBucket}/get-recipes.yaml
      aws s3 cp src/schemas/get-history.yaml s3://${AgentSchemasBucket}/get-history.yaml
      aws s3 cp src/schemas/save-menu.yaml s3://${AgentSchemasBucket}/save-menu.yaml
